{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rivven-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rivven-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rivven-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Prometheus scraping
    - ports:
        - protocol: TCP
          port: {{ (split ":" .Values.operator.metricsAddr)._1 | default "8080" | int }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow Kubernetes API
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
