apiVersion: v1
kind: Service
metadata:
  name: {{ include "rivven-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rivven-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rivven-operator.selectorLabels" . | nindent 4 }}
