apiVersion: v2
name: rivven-operator
description: A Helm chart for deploying the Rivven Kubernetes Operator
type: application
version: 0.0.16
appVersion: "0.0.16"
kubeVersion: ">=1.25.0-0"
keywords:
  - rivven
  - streaming
  - operator
  - kafka-alternative
  - event-streaming
home: https://github.com/hupe1980/rivven
sources:
  - https://github.com/hupe1980/rivven
maintainers:
  - name: hupe1980
    url: https://github.com/hupe1980
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: RivvenCluster
      version: v1alpha1
      name: rivvenclusters.rivven.hupe1980.github.io
      displayName: Rivven Cluster
      description: Represents a Rivven streaming cluster
    - kind: RivvenConnect
      version: v1alpha1
      name: rivvenconnects.rivven.hupe1980.github.io
      displayName: Rivven Connect
      description: Manages CDC and ETL connectors
    - kind: RivvenSchemaRegistry
      version: v1alpha1
      name: rivvenschemaregistries.rivven.hupe1980.github.io
      displayName: Rivven Schema Registry
      description: Confluent-compatible schema registry
